[versions]

kotlin = "2.0.0"

gson = "2.10.1"
gson-extras = "1.3.0"
jansi = "2.4.1"
java-websocket = "1.5.6"
json = "20240303"
jsonschema2pojo = "1.2.1"
kotlinx-serialization-json = "1.7.0"
picocli = "4.7.6"
proguard-gradle = "7.5.0"
miglayout-swing = "11.3"
nexus-publish = "2.0.0"
node-gradle = "7.0.2"
nv-i18n = "1.29"
shadow-jar = "8.1.1"
slf4j-simple = "2.1.0-alpha1"

benmanes-versions = "0.51.0"

[libraries]

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-extras = { module = "org.danilopianini:gson-extras", version.ref = "gson-extras" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
json = { module = "org.json:json", version.ref = "json" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-gradle" }
miglayout-swing = { module = "com.miglayout:miglayout-swing", version.ref = "miglayout-swing" }
nv-i18n = { module = "com.neovisionaries:nv-i18n", version.ref = "nv-i18n" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }

[bundles]

[plugins]

jsonschema2pojo = { id = "org.jsonschema2pojo", version.ref = "jsonschema2pojo" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
shadow-jar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-jar" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }

benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
